version: "3.7"
services: 
    confluence:
        build: 
            context: "${IMAGES}/confluence"
            dockerfile: "Dockerfile"
        image: "dahuzix/docs-confluence:7.3.4"
        container_name: "confluence-7.3.4"
        ports: 
            - "8090:8090"
            - "80:8090"
        restart: "always"
        volumes: 
            - "${VOLUMES}/confluence/application-data:/var/atlassian/application-data/confluence"
    mysql:
        build: 
            context: "${IMAGES}/mysql"
            dockerfile: "Dockerfile"
        image: "dahuzix/docs-mysql:5.7.29"
        container_name: "mysql-5.7.29"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        ports: 
            - "3306:3306"
        restart: "always"
        privileged: true
        volumes: 
            - "${VOLUMES}/mysql/conf:/etc/mysql"
            - "${VOLUMES}/mysql/data:/var/lib/mysql"